[package]
name = "dshot"
description = "Support for the DShot throttle protocol"
authors = ["Robin Schroer <cargo@sulami.xyz>"]
version = "0.1.0"
edition = "2021"
keywords = ["no_std", "embedded-hal"]

[dependencies]
embedded-hal = "1"
