[package]
name = "dshot-frame"
description = "Generates frames for the DShot ESC throttle protocol"
authors = ["Robin Schroer <cargo@sulami.xyz>"]
version = "0.1.0"
edition = "2021"
keywords = ["no_std"]

[dependencies]
